version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-python
      args:
        DEVELOPMENT: 1
    environment:
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT=1
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ${PWD}:/app

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
      args:
        DEVELOPMENT: 1
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ${PWD}:/app
    command: npm run watch
