version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dev/Dockerfile-python
      args:
        DEVELOPMENT: 1
    environment:
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT=1
      - KBASE_ENDPOINT=http://localhost:5011/services
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ${PWD}:/app

  node:
    build:
      context: .
      dockerfile: dev/Dockerfile-node
      args:
        DEVELOPMENT: 1
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ${PWD}:/app
    command: npm run watch

  # Proxy requests from localhost:5011 to ci.kbase.us
  # (for getting around CORS restrictions)
  ci_proxy:
    image: nginx:alpine
    ports:
      - "127.0.0.1:5011:5011"
    volumes:
      - ./dev/nginx-default.conf:/etc/nginx/conf.d/deafult.conf
